In [18]:
L = range(1000000)

In [1]:
import numpy as np

In [20]:
d = np.arange(1000000)

In [66]:
%time for i in range(1,10): r=[x*2 for x in L] 

Wall time: 2.29 s


In [67]:
%time for i in range(1,10): r= d*2  

Wall time: 168 ms


In [74]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
b = np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
np.empty((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [85]:
a = [1,2,34] 
a

[1, 2, 34]

In [86]:
np.array(a)

array([ 1,  2, 34])

In [89]:
a = np.arange(5,100,12)
a

array([ 5, 17, 29, 41, 53, 65, 77, 89])

In [94]:
a = np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:
a.shape

(10, 10)

In [99]:
a.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [100]:
a.ndim

2

In [101]:
a.itemsize

8

In [102]:
a.shape

(10, 10)

In [110]:
a.dtype

dtype('float64')

In [116]:
s = np.random.randn((10))
s

array([ 0.76863765, -1.32240432, -0.08648989,  0.57676908,  0.58626734,
        1.10909942, -0.03598118, -0.75046128, -1.44189267,  0.48965286])

In [117]:
c = np.random.randn((10))
c

array([-0.65570601, -0.2922254 , -0.08876183, -0.55967218, -0.33206684,
       -0.12034846,  2.95503793,  1.38312837,  0.01299822,  0.2413071 ])

In [118]:
s+c

array([ 0.11293164, -1.61462972, -0.17525172,  0.01709691,  0.2542005 ,
        0.98875096,  2.91905675,  0.63266708, -1.42889445,  0.73095996])

In [120]:
s*2

array([ 1.5372753 , -2.64480863, -0.17297978,  1.15353817,  1.17253467,
        2.21819884, -0.07196236, -1.50092257, -2.88378534,  0.97930573])

In [121]:
s+10

array([10.76863765,  8.67759568,  9.91351011, 10.57676908, 10.58626734,
       11.10909942,  9.96401882,  9.24953872,  8.55810733, 10.48965286])

In [122]:
s/3

array([ 0.25621255, -0.44080144, -0.02882996,  0.19225636,  0.19542245,
        0.36969981, -0.01199373, -0.25015376, -0.48063089,  0.16321762])

In [123]:
s>0

array([ True, False, False,  True,  True,  True, False, False, False,
        True])

In [130]:
s[s>0]


array([0.76863765, 0.57676908, 0.58626734, 1.10909942, 0.48965286])

In [134]:
a = np.array([1,2,3,4,5,6])

In [135]:
a[4]

5

In [136]:
a[a>3]

array([4, 5, 6])

In [137]:
a[1:3]

array([2, 3])

In [141]:
a[2:-1]

array([3, 4, 5])

In [193]:
a = np.random.randn(5,5)
a

array([[ 0.45324325, -0.70842621,  1.2431001 , -0.5101051 ,  0.45913484],
       [ 1.84407685,  0.2606337 ,  0.6644311 , -0.25153046, -0.34120891],
       [-0.46387349,  1.9042782 , -0.83366786,  1.89097464, -0.15155182],
       [-0.19102478, -0.33449403, -1.0444999 , -0.37326614, -0.26206586],
       [-0.89399027,  0.45245138, -0.45323922, -1.34400051,  0.55951815]])

In [194]:
a[0,:] # for the row any 

array([ 0.45324325, -0.70842621,  1.2431001 , -0.5101051 ,  0.45913484])

In [160]:
a[0][1]

0.9693757005824776

In [161]:
a[1,:]

array([-0.26938133,  1.48633309,  1.31448341, -0.31281006, -0.73997439])

In [162]:
a[4,:]

array([-0.97024778,  0.01746584, -1.24709215,  0.87006653,  0.2649229 ])

In [199]:
a[1,2:4]

array([ 0.6644311 , -0.25153046])

In [163]:
a[:,1] # for the specific columen

array([ 0.9693757 ,  1.48633309,  0.99731373, -1.14160525,  0.01746584])

In [198]:
a[0:4,:] # for many rows just

array([[ 0.45324325, -0.70842621,  1.2431001 , -0.5101051 ,  0.45913484],
       [ 1.84407685,  0.2606337 ,  0.6644311 , -0.25153046, -0.34120891],
       [-0.46387349,  1.9042782 , -0.83366786,  1.89097464, -0.15155182],
       [-0.19102478, -0.33449403, -1.0444999 , -0.37326614, -0.26206586]])

In [168]:
a[:,0:4] # For the many colums just 

array([[ 0.7134422 ,  0.9693757 ,  0.08844984, -0.50776172],
       [-0.26938133,  1.48633309,  1.31448341, -0.31281006],
       [ 1.39645802,  0.99731373,  0.60986619, -0.11757767],
       [-0.71272483, -1.14160525, -1.04056351,  0.60648431],
       [-0.97024778,  0.01746584, -1.24709215,  0.87006653]])

In [169]:
a[:,1:5]

array([[ 0.9693757 ,  0.08844984, -0.50776172, -1.11905283],
       [ 1.48633309,  1.31448341, -0.31281006, -0.73997439],
       [ 0.99731373,  0.60986619, -0.11757767, -0.23765686],
       [-1.14160525, -1.04056351,  0.60648431,  0.09561316],
       [ 0.01746584, -1.24709215,  0.87006653,  0.2649229 ]])

In [170]:
#Example which allaround are the ones and middles s are the zeros : 

In [189]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [192]:
a[0][1:3]

array([0., 0.])

In [187]:
a[1:-1,1:-1]=1
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [188]:
a[1:-1:2,1:-1:2]=9
a

array([[0., 0., 0., 0., 0.],
       [0., 9., 1., 9., 0.],
       [0., 1., 1., 1., 0.],
       [0., 9., 1., 9., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
Fast functions 

In [202]:
a = np.array([1,2,3,4,5])
b = np.sqrt(a)
b

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [204]:
b = np.power(a,2)
b

array([ 1,  4,  9, 16, 25], dtype=int32)

In [4]:
a =[2,3,4,5]
b= [2,5,6,7]
c = np.maximum(a,b)
c

array([2, 5, 6, 7])

In [6]:
dd

SyntaxError: invalid syntax (<ipython-input-6-f668b8391d92>, line 1)

In [5]:
a = np.array([0,-1,1000,20000])

In [8]:
np.where(a<=0,1000,a)

array([ 1000,  1000,  1000, 20000])

In [16]:
np.where(a<100,400,a)

array([  400,   400,  1000, 20000])

In [2]:
np.where(a<=0,"its ok","Not ok"),


NameError: name 'a' is not defined